// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjcz5K9JYvSTTJBnEokNRQ3T5qg_gP3cg',
    appId: '1:1052567676596:web:0ee76b9a4160b122fad9e1',
    messagingSenderId: '1052567676596',
    projectId: 'mu-flutter-app-notes',
    authDomain: 'mu-flutter-app-notes.firebaseapp.com',
    storageBucket: 'mu-flutter-app-notes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdpWDrr28py2kOH3SBFcy2AT-0wWM-RMM',
    appId: '1:1052567676596:android:f163fddbc4eb54eefad9e1',
    messagingSenderId: '1052567676596',
    projectId: 'mu-flutter-app-notes',
    storageBucket: 'mu-flutter-app-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpb_84CvWP4HijXrwZQXat-_rDxC0kldw',
    appId: '1:1052567676596:ios:94b1b7b9756c09b7fad9e1',
    messagingSenderId: '1052567676596',
    projectId: 'mu-flutter-app-notes',
    storageBucket: 'mu-flutter-app-notes.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpb_84CvWP4HijXrwZQXat-_rDxC0kldw',
    appId: '1:1052567676596:ios:94b1b7b9756c09b7fad9e1',
    messagingSenderId: '1052567676596',
    projectId: 'mu-flutter-app-notes',
    storageBucket: 'mu-flutter-app-notes.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjcz5K9JYvSTTJBnEokNRQ3T5qg_gP3cg',
    appId: '1:1052567676596:web:b1dc71c89416d7f8fad9e1',
    messagingSenderId: '1052567676596',
    projectId: 'mu-flutter-app-notes',
    authDomain: 'mu-flutter-app-notes.firebaseapp.com',
    storageBucket: 'mu-flutter-app-notes.firebasestorage.app',
  );

}